#!/bin/bash
#PBS -q default
#PBS -l walltime=10:00:00
#PBS -l nodes=1:ppn=4
#PBS -W x=NACCESSPOLICY:SHARED
#PBS -N opt-rhf-scf
#PBS -e opt-rhf-scf.stderr
#PBS -o opt-rhf-scf.stdout


#Set job specific environment variables
nodes=`uniq $PBS_NODEFILE`
scr=/var/scratch/alolinco/opt-rhf-scf
jobdir=/home/alolinco/nwc_runs_qcdb/test_check
export ARMCI_DEFAULT_SHMMAX=8000

#Set environment variables for the nwchem version
source /home/weverett/nwchem/6.5-all/env
# Old way of setting stuff
#NWCHEM_DIR=/share/apps/nwchem
#NWCHEM_VER=6.5-all
#DATA_DIR=$NWCHEM_DIR/$NWCHEM_VER/data
#export MPI_LOC=/share/apps/mpi/mvapich2-2.0rc1-mlnx
#export NWCHEM_TOP=$NWCHEM_DIR/$NWCHEM_VER
#export NWCHEM_BASIS_LIBRARY=$DATA_DIR/libraries/
#export NWCHEM_NWPW_LIBRARY=$DATA_DIR/libraryps/
#export AMBER_1=$DATA_DIR/amber_s/
#export AMBER_2=$DATA_DIR/amber_q/
#export AMBER_3=$DATA_DIR/amber_x/
#export AMBER_4=$DATA_DIR/amber_u/
#export SPCE=$DATA_DIR/solvents/spce.rst
#export CHARMM_S=$DATA_DIR/charmm_s/
#export CHARMM_X=$DATA_DIR/charmm_x/
#export PATH=$NWCHEM_TOP/bin:$MPI_LOC/bin:$PATH
#export MANPATH=$NWCHEM_TOP/src/tools/ma/man
#export LD_LIBRARY_PATH=$MPI_LOC/lib:$LD_LIBRARY_PATH

#Print node information and copy files for job
printf "===$(date +"%Y-%m-%d-%r") run nodes===\n$nodes \n" >> $jobdir/opt-rhf-scf.nodes
for i in ${nodes}; do ssh $i "mkdir -p $scr";done
cp $jobdir/opt-rhf-scf.nw $scr
cp $jobdir/*.movecs $scr
cp $jobdir/*.hess $scr

#eval `/usr/bin/modulecmd bash load nwchem/6.5-all`
ulimit -s unlimited
ulimit -c unlimited
cd $scr
mpdboot
mpiexec -np 4 nwchem opt-rhf-scf.nw | tee $jobdir/opt-rhf-scf.out
mpdallexit
cp $scr/*.db $jobdir
cp $scr/*.movecs $jobdir
cp $scr/*.hess $jobdir
cp $scr/ecce* $jobdir
cp $scr/*.log $jobdir
cp $scr/*.out $jobdir

